workflows:
  android-release:
    name: CDCINE Release
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Baixar dependências
        script: flutter packages pub get
      - name: GERAR ÍCONE DO APP (Correção)
        script: dart run flutter_launcher_icons
      - name: Build APK Release
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - seu_email@gmail.com
